# Server
server.port=${PORT:8080}

# Database (use Render environment variables)
spring.datasource.url=jdbc:postgresql://dpg-d7n1rqe8bjmc738k1cf0-a/inventory_db_z7z4
spring.datasource.username=admin
spring.datasource.password=yqKRlR6goyDlGmWF7ybMJRfChRp52qT3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
